version: "3.7"

services:
  frontend:
    image: learning-docker/vue:v1
    ports:
      - "5000:80"
    restart: unless-stopped
  backend:
    image: awesome/database
    volumes:
      - db-data:/etc/data
    networks:
      - back-tier